FROM node:18-alpine
COPY ./ /frontend
WORKDIR /frontend
RUN yarn install --frozen-lockfile && yarn build --mode production

FROM nginx
RUN mkdir /frontend
COPY --from=0 /frontend/dist /frontend
COPY docker/nginx.conf /etc/nginx/nginx.conf

ENV VITE_APP_GOOGLE_MAP_KEY = ${VITE_APP_GOOGLE_MAP_KEY}
